name: CD Example Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: CD Example Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: SSH Connect
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            echo "✅ Berhasil Konek ke Server"
            cd /home/das

            if [ -d ".git" ]; then
              echo "📁 Repo exists, pulling latest changes..."
              git remote set-url origin https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PAT }}@github.com/${{ secrets.GIT_USERNAME }}/cicd_database_example.git
              git pull origin main
            else
              echo "📥 Cloning repo for the first time..."
              git clone https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PAT }}@github.com/${{ secrets.GIT_USERNAME }}/cicd_database_example.git .
            fi

            echo "✅ Deployment finished at $(date)"s
