name: CICD Database Dev to Prod

on:
  push:
    branches:
      - main

jobs:
  db_cicd:
    name: Database CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout My Code
        uses: actions/checkout@v4

      - name: SSH Connect
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Berhasil Connect ke Server."
