name: CICD Database Dev to Prod

on:
  push:
    branches:
      - main
jobs:
  db_cicd:
    name: Database CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout My Code
        uses: actions/checkout@v4 #checkout the code from the repository
      - name: SSH Connect
        uses: appleboy/ssh-action@v1 #ssh action untuk menghubungkan ke server
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Berhasil Connect ke Server."
